config/routes.rb
Rails.application.routes.draw do
  root   'sessions#new'
  post   '/signin',    to: 'sessions#create'
  delete '/signout',   to: 'sessions#destroy'

  get    '/home',      to: 'static_pages#home'
  get    '/search',    to: 'static_pages#search'

  get    '/signup',    to: 'users#new'
  
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  mount_uploader :image, ImageUploader
  
  def self.search(search)
    if search
      Book.where(['title LIKE ?', "%#{search}%"])
    else
      Book.all
    end
  end

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UsersHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = current_user.books.paginate(page: params[:page], per_page: 10)
    @books_count = current_user.books.count
  end

  def show
    @book =current_user.books.find(params[:id])
  end

  def new
    @book = current_user.books.build
  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  def create
    @book = current_user.books.create(book_params)
    if @book
      redirect_to @book
    else
      render 'new'
    end 
  end

  def update
    @book = current_user.books.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end
  
  def destroy
    @book = current_user.books.find(params[:id])
    @book.destroy
    redirect_to home_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :publisher, :genre, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to home_url
		else
      @error_message = 'Invalid email/password combination'
		  render 'new'
		end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @books_count = current_user.books.count
  end

  def search
    @books = current_user.books.search(params[:search])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to home_path
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Book-Manager'
    if page_title.empty?
      base_title
    else
      base_title + ' - ' + page_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでサインインする
  def sign_in(user)
    session[:user_id] = user.id
  end
      
  # 現在のユーザーをサインアウトする
  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/views/books/edit.html.erb
<% provide(:title, 'Book-Edit') %>
    
<%= render 'layouts/header' %>

<main>
  <div class="main-inner">
    <div class="book-edit-form">
      <header class="book-edit-form-title">Book Edit</header>
      
        <%= form_for(@book) do |f| %>
          <%= f.label :title, class: "book-edit-form-label" %>
          <%= f.text_field :title, class: "book-edit-form-input-box" %>

          <%= f.label :publisher, class: "book-edit-form-label" %>
          <%= f.text_field :publisher, class: "book-edit-form-input-box" %>

          <%= f.label :genre, class: "book-edit-form-label" %>
          <%= f.select :genre, [['専門書', '専門書'], ['実用書', '実用書'], ['コミック', 'コミック']],  include_blank: 'Please select.' %>

          <%= f.label :image, class: "book-edit-form-label" %>
          <%= f.file_field :image, class: 'file-select' %>

          <%= f.submit "Update", class: "book-edit-form-button" %>
      <% end %>
    </div>
  </div>  
</main>

app/views/books/index.html.erb
<% provide(:title, 'Books List') %>

<%= render 'layouts/header' %>

<main>
  <div class="main-inner">
    <label class="menu-label">Books List</label>
    
    <ul class="book-list-frame">
      <% @books.each do |book| %>
        <li class="book-list">
          <%= link_to book.title, book_path(book), class: 'book' %>
        </li>    
      <% end %>
    </ul>
    
    <%= will_paginate @books %>
      
    <p class="collection-of-books">Current Collection of Books：<%= @books_count %> books</p>
  </div>
</main>

app/views/books/new.html.erb
<% provide(:title, 'Book-Add') %>
    
<%= render 'layouts/header' %>

<main>
  <div class="main-inner">
    <div class="book-add-form">
      <header class="book-add-form-title">Book Add</header>
      
        <%= form_for(@book) do |f| %>
          <%= f.label :title, class: "book-add-form-label" %>
          <%= f.text_field :title, class: "book-add-form-input-box" %>

          <%= f.label :publisher, class: "book-add-form-label" %>
          <%= f.text_field :publisher, class: "book-add-form-input-box" %>

          <%= f.label :genre, class: "book-add-form-label" %>
          <%= f.select :genre, [['専門書', '専門書'], ['実用書', '実用書'], ['コミック', 'コミック']],  include_blank: 'Please select.' %>

          <%= f.label :image, class: "book-add-form-label" %>
          <%= f.file_field :image, class: 'file-select' %>

          <%= f.submit "Registration", class: "book-add-form-button" %>
      <% end %>
    </div>
  </div>  
</main>

app/views/books/show.html.erb
<% provide(:title, 'Show') %>

<%= render 'layouts/header' %>

<main>
  <div class="main-inner">
    <%= form_for(@book) do |f| %>
      <header class="book-show-form-title">Book Show</header>

      <%= f.label :title, class: "book-show-form-label" %>
      <%= f.text_field :title, class: "book-show-form-input-box" %>

      <%= f.label :publisher, class: "book-show-form-label" %>
      <%= f.text_field :publisher, class: "book-show-form-input-box" %>

      <%= f.label :genre, class: "book-show-form-label" %>
      <%= f.text_field :genre, class: "book-show-form-input-box" %>

      <%= f.label :image, class: "book-show-form-label" %>
      <%= image_tag @book.image.url, class: 'img' %>

      <div class="book-show-button-container">
        <%= link_to 'Edit', edit_book_path, class: 'edit-button' %>
        <%= link_to 'Destroy', book_path, method: :delete, class: 'destroy-button' %>      
      </div>
    <% end %>
  </div>
</main>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header-inner">
    <div class="header-container">
      <div class="header-logo">
        <p><%= link_to image_tag('header-logo-32px.png', alt: 'logo'), home_path %></p>
        <p><%= link_to 'Book-Manager', home_path, class: 'header-logo-title' %></p>
      </div>
      <div class="nav-group">
        <p><%= link_to 'User Profile', current_user, class: 'nav-item' %></p>
        <p><%= link_to 'Sign out', signout_path, method: :delete, class: 'nav-item' %></p>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="body">
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error-message">
    <div>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<%= render 'layouts/header' %>

<main>
  <div class="main-inner">
    <p class="menu-label">Menu</p>
    <div class="menu-container">
      <div class="button">
        <div class="icon"><%= image_tag 'books-list-icon.png', alt: 'books-list-icon' %></div>
        <div class="label"><%= link_to 'Books List', books_path, class: 'link' %></div>
      </div>
      <div class="button">
        <div class="icon"><%= image_tag 'book-search-icon.png', alt: 'book-search-icon' %></div>
        <div class="label"><%= link_to 'Book Search', search_path, class: 'link' %></div>
      </div>
      <div class="button">
        <div class="icon"><%= image_tag 'book-add-icon.png', alt: 'book-add-icon' %></div>
        <div class="label"><%= link_to 'Book Add', new_book_path, class: 'link' %></div>
      </div>
    </div>
    
    <p class="collection-of-books">Current Collection of Books：<%= @books_count %> books</p>
  </div>
</main>

app/views/static_pages/search.html.erb
<% provide(:title, 'Book Search') %>

<%= render 'layouts/header' %>

<div class="main-inner">
  <%= form_tag(search_path,:method => 'get', class: "search-form") do %>
    <header class="book-search-form-title">Book Search</header>
    
    <%= label_tag :search, 'keyword', class: 'search-form-label' %>
    
    <div class="search-container">
      <%= text_field_tag :search, nil, class: 'search-form-input-box' %>
      <%= submit_tag 'Search', class: 'search-form-bottun' %>
    </div>
  <% end %>

  <div class="search-result-label">
    Book Search Result
  </div>

  <ul class="search-result-area">
    <% @books.each do |book| %>
    <li class="search-result-books-list">
      <%= link_to book.title, book, class: 'search-result-books' %>
    </li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>

<div class="signup-inner">
  <%= image_tag 'header-logo-64px.png', class: 'signup-logo', alt: 'book-logo' %>

  <p class="signup-first-message">Welcome to Book-Manager.</p>
  <p class="signup-first-message">Please enter your account.</p>

  <div class="signup-form">
    <header class="signup-form-title">Sign up</header>

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name, class: "signup-form-label" %>
      <%= f.text_field :name, class: "signup-form-input-box" %>

      <%= f.label :email, class: "signup-form-label" %>
      <%= f.email_field :email, class: "signup-form-input-box" %>

      <%= f.label :password, class: "signup-form-label" %>
      <%= f.password_field :password, class: "signup-form-input-box" %>

      <%= f.label :password_confirmation, class: "signup-form-label" %>
      <%= f.password_field :password_confirmation, class: "signup-form-input-box" %>

      <%= f.submit "Sign up", class: "signup-form-button" %>
    <% end %>
  </div>

  <p class="signup-second-message">Do you already have an account?</p>

  <%= link_to "Sign in", root_path, class: 'signin-link-button' %>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User Profile')  %>

<%= render 'layouts/header' %>

<main>
  <div class="main-inner">
    <div class="profile-form">
      <header class="profile-form-title">User profile during sign-in</header>

      <%= form_for(@user) do |f| %>
        <%= f.label :name, class: "profile-label" %>
        <%= f.text_field :name, class: "profile-input-box" %>

        <%= f.label :email, class: "profile-label" %>
        <%= f.email_field :email, class: "profile-input-box" %>
      <% end %>
    </div>
  </div>
</main>